spring.application.name=ZonaDeGolBackEnd


spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

#BBDD
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=1234

spring.datasource.url=jdbc:postgresql://dpg-d185rojuibrs73cabpp0-a.frankfurt-postgres.render.com:5432/zona_de_gol
spring.datasource.username=zona_de_gol_user
spring.datasource.password=BZdnWxLdlGFJMM1wzs5aa3N4JNjzzKwd
spring.datasource.driver-class-name=org.postgresql.Driver



# Correo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=soportezonadegol@gmail.com
spring.mail.password=ywjh veyr xbcm ozpr

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.protocol=smtp

#spring.mail.test-connection=true  # sólo para pruebas





#Stripe
stripe.secretKey = sk_test_51ROjtvCylLezt502FxbNhqabXU86RXAxT1IStf2dYFGr8yrkPgifBHCRLDirfY4dNVRw2FM5LYAiClR45gb0et8d00RB0604CQ

stripe.webhookSecret=whsec_9ae09ed3ed16b7ee5eab450948dc89efa878db815c259c4144d1d08f3a611657

#Puerto
server.port=8080
